"""
humanoid_rig.py — headless-Blender auto-rig for GYRE's forge humanoids.

Pipeline (all CLI / autonomous, run under `blender -b -P`):

    import GLB  ->  build a humanoid armature from a PROPORTION CONFIG
                ->  skin with automatic (heat) weights
                ->  clean weights (limit total + smooth) so arms-down auto-weights
                    don't bleed arm into torso
                ->  author a small CLIP set (idle / cast / guard / strike / hit)
                    as separate Actions pushed to NLA tracks
                ->  export a rigged + animated GLB (glTF binary, skinning + anims)

Coordinate facts for the ld-player sculpts (already established, do not re-derive):
  * The glTF importer converts Y-up -> Blender Z-up, so the character stands along Z.
  * Normalized bbox: height 1.0 along Z, feet at Z = -0.5, head top at Z = +0.5,
    centered on X/Y ~= 0. Character faces -Y (that is the camera-facing front).
  * Bone placement below is expressed as FRACTIONS of height, so any ld-player
    sculpt (which is normalized the same way) reuses this rig.

Usage:
    blender -b -P humanoid_rig.py -- \
        --in <input.glb> --out <rigged.glb> \
        [--render-dir <dir>]      # if set, also render rest/cast/guard verification PNGs
        [--no-export]             # skip GLB export (render-only iteration)
"""

import bpy
import sys
import os
import math
import mathutils


# --------------------------------------------------------------------------- #
# arg parsing (everything after the standalone "--")
# --------------------------------------------------------------------------- #
def parse_args():
    argv = sys.argv
    args = argv[argv.index("--") + 1:] if "--" in argv else []
    out = {"in": None, "out": None, "render_dir": None, "export": True}
    i = 0
    while i < len(args):
        a = args[i]
        if a == "--in":
            out["in"] = args[i + 1]; i += 2
        elif a == "--out":
            out["out"] = args[i + 1]; i += 2
        elif a == "--render-dir":
            out["render_dir"] = args[i + 1]; i += 2
        elif a == "--no-export":
            out["export"] = False; i += 1
        else:
            i += 1
    return out


# --------------------------------------------------------------------------- #
# PROPORTION CONFIG — fractions-of-height space.
#
# The sculpt is normalized to height 1.0 (feet Z=-0.5, head Z=+0.5, X/Y~=0),
# so these are literal Blender coordinates for this test mesh AND fractional
# for any other ld-player sculpt (we re-normalize incoming meshes to match).
#
# Arms hang DOWNWARD (arms-down neutral pose), so arm/leg bones run -Z.
# Left side is +X; we mirror to -X for .R. "front" is -Y.
#
# Each bone: name -> (head_xyz, tail_xyz, parent_or_None, is_mirrored)
# Mirrored bones are authored on the +X (.L) side; .R is generated by X-flip.
# --------------------------------------------------------------------------- #
SPINE_CHAIN = [
    # name,    head,               tail,               parent
    ("hips",  (0.00, 0.00, 0.02), (0.00, 0.00, 0.02), None),   # root; tiny, oriented up
    ("spine", (0.00, 0.00, 0.02), (0.00, 0.00, 0.16), "hips"),
    ("chest", (0.00, 0.00, 0.16), (0.00, 0.00, 0.30), "spine"),
    ("neck",  (0.00, 0.00, 0.34), (0.00, 0.00, 0.40), "chest"),
    ("head",  (0.00, 0.00, 0.40), (0.00, 0.00, 0.50), "neck"),
]

# Limb bones authored on the LEFT (+X) side. Parent is a spine bone or the
# previous limb bone. These get mirrored to .R automatically.
LIMBS_L = [
    # name,        head,                 tail,                 parent
    ("clavicle", (0.020, 0.00, 0.305), (0.090, 0.00, 0.300), "chest"),
    ("upperarm", (0.090, 0.00, 0.300), (0.130, 0.00, 0.080), "clavicle"),
    ("forearm",  (0.130, 0.00, 0.080), (0.122, 0.00, -0.130), "upperarm"),
    ("hand",     (0.122, 0.00, -0.130), (0.118, 0.00, -0.195), "forearm"),
    ("thigh",    (0.052, 0.00, 0.010), (0.050, 0.00, -0.230), "hips"),
    ("shin",     (0.050, 0.00, -0.230), (0.046, 0.00, -0.460), "thigh"),
    ("foot",     (0.046, 0.00, -0.460), (0.046, -0.075, -0.500), "shin"),
]

# The "hips" root needs a non-zero length; give it a short upward nub so Blender
# keeps it. (head==tail bones get deleted.)
HIPS_TAIL = (0.00, 0.00, 0.055)


# --------------------------------------------------------------------------- #
# helpers
# --------------------------------------------------------------------------- #
def log(*a):
    print("[rig]", *a)
    sys.stdout.flush()


def clean_scene():
    bpy.ops.wm.read_factory_settings(use_empty=True)


def import_glb(path):
    bpy.ops.import_scene.gltf(filepath=path)
    meshes = [o for o in bpy.data.objects if o.type == "MESH"]
    if not meshes:
        raise RuntimeError("no mesh in imported GLB")
    # join into one object if the sculpt came in as several parts
    mesh = meshes[0]
    if len(meshes) > 1:
        bpy.ops.object.select_all(action="DESELECT")
        for m in meshes:
            m.select_set(True)
        bpy.context.view_layer.objects.active = mesh
        bpy.ops.object.join()
    # apply transforms so world == local (importer leaves a rotation on the root)
    bpy.ops.object.select_all(action="DESELECT")
    mesh.select_set(True)
    bpy.context.view_layer.objects.active = mesh
    bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
    return mesh


def mesh_bounds(mesh):
    corners = [mesh.matrix_world @ mathutils.Vector(c) for c in mesh.bound_box]
    xs = [c.x for c in corners]; ys = [c.y for c in corners]; zs = [c.z for c in corners]
    return (min(xs), max(xs), min(ys), max(ys), min(zs), max(zs))


def normalize_mesh(mesh):
    """Re-normalize any incoming sculpt to the canonical frame: height 1.0 along Z,
    feet at Z=-0.5, centered on X/Y. Keeps the proportion config valid for every
    ld-player mesh, not just the test one."""
    minx, maxx, miny, maxy, minz, maxz = mesh_bounds(mesh)
    height = maxz - minz
    if height < 1e-6:
        raise RuntimeError("degenerate mesh height")
    scale = 1.0 / height
    cx = (minx + maxx) / 2.0
    cy = (miny + maxy) / 2.0
    # move so center X/Y -> 0, feet Z -> -0.5
    mesh.location = (-cx * scale, -cy * scale, -(minz * scale) - 0.5)
    mesh.scale = (scale, scale, scale)
    bpy.context.view_layer.objects.active = mesh
    bpy.ops.object.select_all(action="DESELECT")
    mesh.select_set(True)
    bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
    b = mesh_bounds(mesh)
    log("normalized bbox x", round(b[0], 3), round(b[1], 3),
        "y", round(b[2], 3), round(b[3], 3),
        "z", round(b[4], 3), round(b[5], 3))
    return mesh


def mirror_x(v):
    return (-v[0], v[1], v[2])


def build_armature():
    """Build the humanoid armature from the proportion config. Returns the
    armature object (in object mode)."""
    arm_data = bpy.data.armatures.new("humanoid")
    arm_obj = bpy.data.objects.new("humanoid", arm_data)
    bpy.context.scene.collection.objects.link(arm_obj)
    bpy.context.view_layer.objects.active = arm_obj
    arm_obj.select_set(True)

    bpy.ops.object.mode_set(mode="EDIT")
    ebones = arm_data.edit_bones

    def add(name, head, tail, parent_name):
        eb = ebones.new(name)
        eb.head = head
        eb.tail = tail
        if parent_name and parent_name in ebones:
            eb.parent = ebones[parent_name]
            eb.use_connect = False
        return eb

    # spine chain (centre bones, no mirroring)
    for name, head, tail, parent in SPINE_CHAIN:
        if name == "hips":
            add(name, head, HIPS_TAIL, parent)
        else:
            add(name, head, tail, parent)

    # left limbs only. The RIGHT side is generated by armature.symmetrize()
    # below — doing it that way (rather than a manual X-flip of head/tail) is
    # essential: symmetrize also mirrors each bone's ROLL, so a given local-axis
    # rotation deforms .L and .R identically. A naive X-flip leaves .R with the
    # wrong local axes, so the same keyframe rotates the .R arm INTO the body
    # and tears the shoulder.
    for name, head, tail, parent in LIMBS_L:
        add(name + ".L", head, tail, parent)

    # symmetrize .L -> .R with correct mirrored roll.
    bpy.ops.armature.select_all(action="SELECT")
    bpy.ops.armature.symmetrize(direction="POSITIVE_X")

    bpy.ops.object.mode_set(mode="OBJECT")
    log("armature bones:", len(arm_data.bones))
    return arm_obj


def skin(mesh, arm_obj, clean=True):
    """Parent mesh to armature with automatic (heat) weights, then clean the
    weights so arms-down auto-weights don't bleed the arm into the torso."""
    bpy.ops.object.select_all(action="DESELECT")
    mesh.select_set(True)
    arm_obj.select_set(True)
    bpy.context.view_layer.objects.active = arm_obj
    bpy.ops.object.parent_set(type="ARMATURE_AUTO")

    if not clean:
        log("skinned (raw auto-weights, no cleanup)")
        return

    # --- weight cleanup -----------------------------------------------------
    # 1) limit total influences per vertex to 4 (glTF-friendly, kills stray
    #    long-range bleed) and normalize.
    # 2) a light smooth pass to soften the shoulder/deltoid seam that arms-down
    #    heat weights leave (verified: reduces the shoulder tear-flap).
    # NOTE: select all verts in EDIT mode first, or the ops act on a stale
    # selection / silently no-op.
    bpy.ops.object.select_all(action="DESELECT")
    mesh.select_set(True)
    bpy.context.view_layer.objects.active = mesh
    bpy.ops.object.mode_set(mode="EDIT")
    bpy.ops.mesh.select_all(action="SELECT")
    bpy.ops.object.vertex_group_limit_total(limit=4)
    bpy.ops.object.vertex_group_normalize_all(lock_active=False)
    bpy.ops.object.mode_set(mode="OBJECT")

    bpy.ops.object.mode_set(mode="WEIGHT_PAINT")
    bpy.ops.object.vertex_group_smooth(group_select_mode="ALL", factor=0.5, repeat=3)
    bpy.ops.object.mode_set(mode="OBJECT")
    log("skinned + weight-cleaned")


# --------------------------------------------------------------------------- #
# animation authoring
# --------------------------------------------------------------------------- #
def _pose_bone(arm_obj, name):
    return arm_obj.pose.bones.get(name)


def _key_rot(arm_obj, name, frame, euler_xyz):
    """Set a bone's local rotation (XYZ euler, radians) and keyframe it."""
    pb = _pose_bone(arm_obj, name)
    if not pb:
        return
    pb.rotation_mode = "XYZ"
    pb.rotation_euler = mathutils.Euler(euler_xyz, "XYZ")
    pb.keyframe_insert(data_path="rotation_euler", frame=frame)


def _key_loc(arm_obj, name, frame, loc_xyz):
    pb = _pose_bone(arm_obj, name)
    if not pb:
        return
    pb.location = loc_xyz
    pb.keyframe_insert(data_path="location", frame=frame)


def _reset_pose(arm_obj):
    for pb in arm_obj.pose.bones:
        pb.rotation_mode = "XYZ"
        pb.rotation_euler = (0, 0, 0)
        pb.location = (0, 0, 0)


def _new_action(arm_obj, name):
    _reset_pose(arm_obj)
    act = bpy.data.actions.new(name)
    if not arm_obj.animation_data:
        arm_obj.animation_data_create()
    arm_obj.animation_data.action = act
    return act


def _push_to_nla(arm_obj, act):
    """Push the current action to its own NLA track so the GLB exporter emits it
    as a separate glTF AnimationClip."""
    ad = arm_obj.animation_data
    track = ad.nla_tracks.new()
    track.name = act.name
    track.strips.new(act.name, int(act.frame_range[0]), act)
    ad.action = None


D = math.radians  # degrees -> radians shorthand

# Bones deform arms that hang DOWN. To raise an arm forward (toward -Y front),
# we rotate the upperarm about local X. The sign that lifts the arm forward was
# found by rendering; documented at each use.


def author_idle(arm_obj):
    """Slow breathing + weight sway. Loops 1..96 (~4s at 24fps)."""
    _new_action(arm_obj, "idle")
    f0, fh, f1 = 1, 48, 96
    for f, s in ((f0, 0.0), (fh, 1.0), (f1, 0.0)):
        # subtle chest lift + hips sway
        _key_rot(arm_obj, "chest", f, (D(-2.0) * s, 0, 0))
        _key_rot(arm_obj, "spine", f, (D(1.0) * s, 0, 0))
        _key_rot(arm_obj, "hips", f, (0, 0, D(1.5) * s))
        _key_rot(arm_obj, "head", f, (0, 0, D(2.0) * s))
        # arms drift very slightly out
        _key_rot(arm_obj, "upperarm.L", f, (0, 0, D(3.0) * s))
        _key_rot(arm_obj, "upperarm.R", f, (0, 0, D(-3.0) * s))
    act = arm_obj.animation_data.action
    act.use_frame_range = True
    act.frame_start, act.frame_end = f0, f1
    _push_to_nla(arm_obj, act)


def author_cast(arm_obj):
    """Both arms raise up/forward — the 'arms up to receive/cast' gesture.
    Hold at the peak, then settle. 1..60."""
    _new_action(arm_obj, "cast")
    f0, fpeak, f1 = 1, 40, 60
    # rest
    for f in (f0,):
        _key_rot(arm_obj, "upperarm.L", f, (0, 0, 0))
        _key_rot(arm_obj, "upperarm.R", f, (0, 0, 0))
        _key_rot(arm_obj, "forearm.L", f, (0, 0, 0))
        _key_rot(arm_obj, "forearm.R", f, (0, 0, 0))
        _key_rot(arm_obj, "chest", f, (0, 0, 0))
        _key_rot(arm_obj, "head", f, (0, 0, 0))
    # peak: arms swing up & forward — the "arms up to receive/cast" gesture.
    # upperarm rotates about local X to lift the hanging arm up/forward; +X on
    # .L, mirrored on .R (symmetrized roll makes the same sign lift both). Kept
    # at ~100 deg: past ~120 the shoulder skin inverts and tears under
    # auto-weights (verified by render), so we stay in the clean range and add a
    # small clavicle raise + elbow bend to read as "reaching up".
    for f in (fpeak, f1 - 4):
        _key_rot(arm_obj, "clavicle.L", f, (0, 0, D(-14)))
        _key_rot(arm_obj, "clavicle.R", f, (0, 0, D(14)))
        _key_rot(arm_obj, "upperarm.L", f, (D(100), 0, D(10)))
        _key_rot(arm_obj, "upperarm.R", f, (D(100), 0, D(-10)))
        _key_rot(arm_obj, "forearm.L", f, (D(-40), 0, 0))
        _key_rot(arm_obj, "forearm.R", f, (D(-40), 0, 0))
        _key_rot(arm_obj, "chest", f, (D(-6), 0, 0))   # lean back slightly
        _key_rot(arm_obj, "head", f, (D(-6), 0, 0))    # look up
    # settle back toward peak (hold-ish)
    _key_rot(arm_obj, "upperarm.L", f1, (D(92), 0, D(9)))
    _key_rot(arm_obj, "upperarm.R", f1, (D(92), 0, D(-9)))
    act = arm_obj.animation_data.action
    act.use_frame_range = True
    act.frame_start, act.frame_end = f0, f1
    _push_to_nla(arm_obj, act)


def author_guard(arm_obj):
    """Kneel back + brace: bend knees, sink hips, lean torso back, arms come up
    to guard. 1..50."""
    _new_action(arm_obj, "guard")
    f0, fpeak, f1 = 1, 35, 50
    for f in (fpeak, f1):
        s = 1.0 if f == fpeak else 0.92
        # sink & bend into a braced crouch. Angles kept in the clean range
        # verified by render: thigh forward ~32, shin folds back ~-28 so the
        # lower leg stays roughly under the body (past ~-45 the knee tears),
        # small foot counter-rotation. Hips sink and pelvis tilts back.
        _key_loc(arm_obj, "hips", f, (0, 0, -0.07 * s))     # sink down
        _key_rot(arm_obj, "hips", f, (D(-8) * s, 0, 0))     # tilt pelvis back
        _key_rot(arm_obj, "thigh.L", f, (D(32) * s, 0, D(6)))
        _key_rot(arm_obj, "thigh.R", f, (D(32) * s, 0, D(-6)))
        _key_rot(arm_obj, "shin.L", f, (D(-28) * s, 0, 0))
        _key_rot(arm_obj, "shin.R", f, (D(-28) * s, 0, 0))
        _key_rot(arm_obj, "foot.L", f, (D(6) * s, 0, 0))
        _key_rot(arm_obj, "foot.R", f, (D(6) * s, 0, 0))
        # torso leans back, arms raise to a braced guard (in the clean arm range)
        _key_rot(arm_obj, "spine", f, (D(8) * s, 0, 0))
        _key_rot(arm_obj, "chest", f, (D(5) * s, 0, 0))
        _key_rot(arm_obj, "upperarm.L", f, (D(58) * s, 0, D(16)))
        _key_rot(arm_obj, "upperarm.R", f, (D(58) * s, 0, D(-16)))
        _key_rot(arm_obj, "forearm.L", f, (D(-70) * s, 0, 0))
        _key_rot(arm_obj, "forearm.R", f, (D(-70) * s, 0, 0))
    # rest frame
    for name in ("hips", "thigh.L", "thigh.R", "shin.L", "shin.R", "foot.L",
                 "foot.R", "spine", "chest", "upperarm.L", "upperarm.R",
                 "forearm.L", "forearm.R"):
        _key_rot(arm_obj, name, f0, (0, 0, 0))
    _key_loc(arm_obj, "hips", f0, (0, 0, 0))
    act = arm_obj.animation_data.action
    act.use_frame_range = True
    act.frame_start, act.frame_end = f0, f1
    _push_to_nla(arm_obj, act)


def author_strike(arm_obj):
    """Step + swing the right arm forward. 1..40."""
    _new_action(arm_obj, "strike")
    f0, fwind, fhit, f1 = 1, 12, 26, 40
    # rest
    for name in ("upperarm.R", "forearm.R", "chest", "neck", "hips", "thigh.R"):
        _key_rot(arm_obj, name, f0, (0, 0, 0))
    # wind up: arm back, torso coils. Twist is spread across chest+neck (a
    # single hard chest-Z twist crimps the neck junction — verified by render).
    _key_rot(arm_obj, "upperarm.R", fwind, (D(-40), 0, D(-25)))
    _key_rot(arm_obj, "forearm.R", fwind, (D(-30), 0, 0))
    _key_rot(arm_obj, "chest", fwind, (0, 0, D(-12)))
    _key_rot(arm_obj, "neck", fwind, (0, 0, D(6)))
    _key_rot(arm_obj, "hips", fwind, (0, 0, D(-8)))
    # hit: arm swings forward/down, torso uncoils, small step (thigh forward)
    _key_rot(arm_obj, "upperarm.R", fhit, (D(95), 0, D(10)))
    _key_rot(arm_obj, "forearm.R", fhit, (D(-20), 0, 0))
    _key_rot(arm_obj, "chest", fhit, (0, 0, D(14)))
    _key_rot(arm_obj, "neck", fhit, (0, 0, D(-6)))
    _key_rot(arm_obj, "hips", fhit, (0, 0, D(10)))
    _key_rot(arm_obj, "thigh.R", fhit, (D(25), 0, 0))
    # recover toward neutral
    for name in ("upperarm.R", "forearm.R", "chest", "neck", "hips", "thigh.R"):
        _key_rot(arm_obj, name, f1, (0, 0, 0))
    act = arm_obj.animation_data.action
    act.use_frame_range = True
    act.frame_start, act.frame_end = f0, f1
    _push_to_nla(arm_obj, act)


def author_hit(arm_obj):
    """Short recoil back. 1..24."""
    _new_action(arm_obj, "hit")
    f0, fpeak, f1 = 1, 8, 24
    for name in ("spine", "chest", "head", "hips"):
        _key_rot(arm_obj, name, f0, (0, 0, 0))
    _key_loc(arm_obj, "hips", f0, (0, 0, 0))
    # recoil: torso snaps back, head flicks, hips shift back
    _key_rot(arm_obj, "spine", fpeak, (D(14), 0, 0))
    _key_rot(arm_obj, "chest", fpeak, (D(10), 0, 0))
    _key_rot(arm_obj, "head", fpeak, (D(16), 0, 0))
    _key_loc(arm_obj, "hips", fpeak, (0, 0.03, -0.02))
    _key_rot(arm_obj, "upperarm.L", fpeak, (0, 0, D(20)))
    _key_rot(arm_obj, "upperarm.R", fpeak, (0, 0, D(-20)))
    # settle
    for name in ("spine", "chest", "head", "upperarm.L", "upperarm.R"):
        _key_rot(arm_obj, name, f1, (0, 0, 0))
    _key_loc(arm_obj, "hips", f1, (0, 0, 0))
    act = arm_obj.animation_data.action
    act.use_frame_range = True
    act.frame_start, act.frame_end = f0, f1
    _push_to_nla(arm_obj, act)


def ease_all_actions():
    """Give every keyframe a smooth (slow, weighty) interpolation."""
    for act in bpy.data.actions:
        for fc in act.fcurves:
            for kp in fc.keyframe_points:
                kp.interpolation = "BEZIER"
                kp.handle_left_type = "AUTO_CLAMPED"
                kp.handle_right_type = "AUTO_CLAMPED"


# --------------------------------------------------------------------------- #
# verification render (WORKBENCH, ORTHO cam, TRACK_TO, Z-up) — front view
# --------------------------------------------------------------------------- #
def setup_render_camera():
    scene = bpy.context.scene
    scene.render.engine = "BLENDER_WORKBENCH"
    scene.display.shading.light = "MATCAP"
    scene.render.resolution_x = 420
    scene.render.resolution_y = 640
    scene.render.film_transparent = False

    target = bpy.data.objects.new("rig_target", None)
    target.location = (0, 0, 0)
    scene.collection.objects.link(target)

    cam_data = bpy.data.cameras.new("rig_cam")
    cam_data.type = "ORTHO"
    cam_data.ortho_scale = 1.4
    cam = bpy.data.objects.new("rig_cam", cam_data)
    scene.collection.objects.link(cam)
    scene.camera = cam
    con = cam.constraints.new("TRACK_TO")
    con.target = target
    con.track_axis = "TRACK_NEGATIVE_Z"
    con.up_axis = "UP_Y"
    # front view: look from -Y (character faces -Y), slightly toward +X so raised
    # arms read in depth. Distance along -Y.
    cam.location = (0.35, -2.5, 0.0)
    return scene, cam


def render_pose(scene, arm_obj, action_name, frame, path):
    """Set the armature to a given action+frame and render a still.

    Crucial: fully reset every pose bone first, because each clip only keys a
    subset of bones — without a reset, bones keyed by a *previous* clip stay
    posed and the render tears. (Export is unaffected: each NLA strip carries a
    complete action, evaluated independently.)"""
    ad = arm_obj.animation_data
    act = bpy.data.actions.get(action_name) if action_name else None
    _reset_pose(arm_obj)
    ad.action = act
    scene.frame_set(int(frame))
    bpy.context.view_layer.update()
    scene.render.filepath = path
    bpy.ops.render.render(write_still=True)
    log("rendered", os.path.basename(path), "(", action_name, "frame", frame, ")")


# --------------------------------------------------------------------------- #
# export
# --------------------------------------------------------------------------- #
def export_glb(path, mesh, arm_obj):
    bpy.ops.object.select_all(action="DESELECT")
    mesh.select_set(True)
    arm_obj.select_set(True)
    bpy.context.view_layer.objects.active = arm_obj
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    bpy.ops.export_scene.gltf(
        filepath=path,
        export_format="GLB",
        use_selection=True,
        export_yup=True,
        export_skins=True,
        export_animations=True,
        export_animation_mode="ACTIONS",   # one glTF clip per NLA action
        export_nla_strips=True,
        export_apply=False,
    )
    log("exported", path)


# --------------------------------------------------------------------------- #
# main
# --------------------------------------------------------------------------- #
def main():
    args = parse_args()
    if not args["in"]:
        raise SystemExit("need --in <glb>")
    log("input:", args["in"])

    clean_scene()
    mesh = import_glb(args["in"])
    normalize_mesh(mesh)
    arm_obj = build_armature()
    skin(mesh, arm_obj, clean=(os.environ.get("RIG_NOCLEAN") != "1"))

    # author clips
    author_idle(arm_obj)
    author_cast(arm_obj)
    author_guard(arm_obj)
    author_strike(arm_obj)
    author_hit(arm_obj)
    ease_all_actions()
    log("actions:", [a.name for a in bpy.data.actions])

    # verification renders
    if args["render_dir"]:
        os.makedirs(args["render_dir"], exist_ok=True)
        scene, cam = setup_render_camera()
        rd = args["render_dir"]
        render_pose(scene, arm_obj, None, 1, os.path.join(rd, "rest.png"))
        render_pose(scene, arm_obj, "cast", 40, os.path.join(rd, "cast.png"))
        render_pose(scene, arm_obj, "guard", 35, os.path.join(rd, "guard.png"))
        render_pose(scene, arm_obj, "strike", 26, os.path.join(rd, "strike.png"))
        render_pose(scene, arm_obj, "hit", 8, os.path.join(rd, "hit.png"))
        # a 3/4 side view of the guard crouch to read knee bend + depth
        cam.location = (1.6, -1.9, 0.05)
        render_pose(scene, arm_obj, "guard", 35, os.path.join(rd, "guard_side.png"))
        cam.location = (0.35, -2.5, 0.0)
        # reset to rest for a clean export
        arm_obj.animation_data.action = None
        scene.frame_set(1)

    if args["export"] and args["out"]:
        export_glb(args["out"], mesh, arm_obj)

    log("DONE")


if __name__ == "__main__":
    main()
