import type { RobloxDescriptor, SocketSchema } from "./schema";

/**
 * Emit a self-contained Luau script that rebuilds a descriptor as a Roblox
 * `Model` — the web→Roblox half of the bridge. The browser greybox (see
 * descriptorToThree.ts) is for *preview*; this is the artifact you paste into
 * Roblox Studio's command bar / a Script to materialise the same assembly.
 *
 * Units stay in **studs** here — Roblox is stud-native, so we do NOT apply the
 * STUDS_TO_M conversion (that's a three.js-render concern only). Each socket
 * becomes an Anchored `Part` sized + offset from a root part's CFrame, all
 * parented into one `Model`. Returns the script text; `buildModel()` inside it
 * returns the assembled Model so callers can place it where they like.
 *
 * Pure — string in, string out, no three.js / DOM. Hex parsing handles both
 * `#rgb` and `#rrggbb`.
 */
export function descriptorToLuau(
  descriptor: RobloxDescriptor,
  schema: SocketSchema,
): string {
  const [r, g, b] = hexToRgb(descriptor.color);
  const entries = Object.entries(schema);

  const partLines = entries.map(([socketName, socket]) => {
    const [sx, sy, sz] = socket.size;
    const [px, py, pz] = socket.position;
    const varName = sanitizeVar(socketName);
    return [
      `\t-- ${socketName}`,
      `\tlocal ${varName} = Instance.new("Part")`,
      `\t${varName}.Name = ${luaString(socketName)}`,
      `\t${varName}.Anchored = true`,
      `\t${varName}.Size = Vector3.new(${num(sx)}, ${num(sy)}, ${num(sz)})`,
      `\t${varName}.CFrame = root.CFrame * CFrame.new(${num(px)}, ${num(py)}, ${num(pz)})`,
      `\t${varName}.Color = Color3.fromRGB(${r}, ${g}, ${b})`,
      `\t${varName}.Parent = model`,
    ].join("\n");
  });

  return `-- Crucible Roblox descriptor: ${descriptor.id} (archetype: ${descriptor.archetype})
-- Generated by descriptorToLuau. Units are Roblox studs.
-- ${entries.length} socket part(s) + 1 root part.

local function buildModel()
\tlocal model = Instance.new("Model")
\tmodel.Name = ${luaString(descriptor.id)}

\t-- Root anchor part; every socket is offset from its CFrame.
\tlocal root = Instance.new("Part")
\troot.Name = "Root"
\troot.Anchored = true
\troot.Transparency = 1
\troot.Size = Vector3.new(1, 1, 1)
\troot.CFrame = CFrame.new(0, 0, 0)
\troot.Color = Color3.fromRGB(${r}, ${g}, ${b})
\troot.Parent = model
\tmodel.PrimaryPart = root

${partLines.join("\n\n")}

\treturn model
end

local model = buildModel()
model.Parent = workspace
return model
`;
}

/** Parse a `#rgb` or `#rrggbb` hex string into `[r, g, b]` 0–255 ints. */
function hexToRgb(hex: string): [number, number, number] {
  const h = hex.replace(/^#/, "");

  if (h.length === 3) {
    const r = h[0] ?? "0";
    const g = h[1] ?? "0";
    const b = h[2] ?? "0";
    return [
      parseInt(r + r, 16),
      parseInt(g + g, 16),
      parseInt(b + b, 16),
    ];
  }

  // #rrggbb (schema guarantees one of the two lengths; default safely anyway).
  const rr = h.slice(0, 2) || "00";
  const gg = h.slice(2, 4) || "00";
  const bb = h.slice(4, 6) || "00";
  return [parseInt(rr, 16), parseInt(gg, 16), parseInt(bb, 16)];
}

/** Format a number for Luau: trim to a tidy fixed precision, drop `-0`. */
function num(n: number): string {
  const fixed = Number.parseFloat(n.toFixed(4));
  return Object.is(fixed, -0) ? "0" : String(fixed);
}

/** Quote a string as a Luau literal (escape backslash + double-quote). */
function luaString(s: string): string {
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

/** Make a safe Luau local-variable name from a socket name. */
function sanitizeVar(name: string): string {
  const cleaned = name.replace(/[^A-Za-z0-9_]/g, "_");
  return /^[A-Za-z_]/.test(cleaned) ? `part_${cleaned}` : `part__${cleaned}`;
}
